images_path: images/
labels_path: labels/
dataset_path: dataset/
output_path: output/

active_learning:
  model: "models/ssl.pt"
  images_per_iteration: 100
  num_clusters: 1000
  output_file_name: "active_learning_images.txt"
  embeddings_file_name: "embeddings.csv"

inference:
  confidence_threshold: 0.25
  agnostic_nms: True
  half: False
  image_size: 960
