raw_images_path: raw_images/
labels_path: labels/
dataset_path: dataset/
output_path: output/

dataset:
  val_split: 0.2
  balance_classes: True

active_learning:
  model: "models/best.pt"
  images_per_iteration: 1000
  num_clusters: 50
  output_file_name: "active_learning_images.txt"
  embeddings_file_name: "embeddings.csv"

inference:
  confidence_threshold: 0.25
  agnostic_nms: True
  half: False
