yolo:
  model: yolo11n.pt
  resume: False
  amp: False
  compile: True

  epochs: 300
  patience: 100
  batch: 64
  device: [0, 1]
  optimizer: 'AdamW'
  lr: 0.001

  augmentation:
    hsv_h: 0.08 # Hue, don't change hue as it affects colors
    hsv_s: 0.5 # Saturation
    hsv_v: 0.5 # Brightness
    degrees: 20.0 # Tilt image
    flipud: 0.0 # Flip upside down
    fliplr: 0.0 # Flip left to right
    mosaic: 1.0 # Tile multiple images together
    scale: 0.5 # Zoom in/out

ssl:
  out_dir: 'pretrain_runs'
  model: 'ultralytics/yolo11n.pt'

  epochs: 100
  batch: 512

  accelerator: 'gpu'
  devices: 2
  overwrite: True

  teacher: 'dinov3/vitb16'
